apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: netop-manager-system-kube-root-ca.crt-configmap-core-v1
spec:
  clusterName: calicogf
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: kube-root-ca.crt
    namespace: netop-manager-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"kube-root-ca.crt","namespace":"netop-manager-system","creationTimestamp":null},"data":{"ca.crt":"-----BEGIN
    CERTIFICATE-----\nMIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl\ncm5ldGVzMB4XDTIyMTExNzE5NTEwOFoXDTMyMTExNDE5NTEwOFowFTETMBEGA1UE\nAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALo2\n3k5XL5rTLYbjlZZESJcpr5YZiu/1CbD6fCyHuO3q27lceCivOMnIMbHqgiyTWSOs\nBt6GlZdaF2sDcpa6k2Ih98vehSWXwsTmceKztYJDEJ/HQxKta72aU1jt41aIA9JM\nreDcWGeEo6EM0tuzRV6kywbeLV5KMUZNHKKnKB5ZPIBei77fFZFbHYLdlN1T2zHZ\nDMl3t1zKvnFl4gRrXYJwvRJeJWVEImpO3gik4xc4cqzsWAp0WzP1XnlzjmlFGWJZ\nIUTgOPAEHtyVs966oUh5C8LURVaTlxYUbHlzZRdZdAfkfzDPT3+p7rNNLCNdLX9g\nRMsOeVN/WtkWu12h3zECAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB\n/wQFMAMBAf8wHQYDVR0OBBYEFFVXIhB59rUJtPeZn/erHg1OBTsLMBUGA1UdEQQO\nMAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAKK1a+e9BlCraZW0tLVQ\n5GN2HABXCdZ2QnCzN/5jcsM1Fmm3LmX7UeB1aprkNziM548IlJWwF5C9zCcKnfD3\nl+pUO6CPnhIJuQr9lheAkIE1nxLp4Y6SradggYf5H3YObFelfOYAq/ubheXvlP2e\nMpQV3YslbV08yexC/2IDciidRlRY3YaL5Fzs5siIJvLFwFRFEOvRhyJZ2KLCdvaA\nbgv2/671dligqtl51eRQjU8pon9cW+7EPUtjDtS6L2eDos4CzsJ/j8oNr2yjOISC\n0zJ/qyqvLqhzBapuzeywGJoyn/0h9CCnneJqRE6HUgCIzvWO6S/JKa2ShnoNmQnD\nDsg=\n-----END
    CERTIFICATE-----\n"}}'
status:
  state: ""
